const availableSongs = [
  { name: "Stairway to Heaven", artist: "Led Zeppelin", genre: "Classic Rock" },
  { name: "Sweet Child O' Mine", artist: "Guns N' Roses", genre: "Rock" },
  { name: "Hotel California", artist: "Eagles", genre: "Rock" },
  { name: "Smoke on the Water", artist: "Deep Purple", genre: "Hard Rock" },
  { name: "Born to Run", artist: "Bruce Springsteen", genre: "Rock" },
  { name: "Free Bird", artist: "Lynyrd Skynyrd", genre: "Southern Rock" },
  { name: "Layla", artist: "Derek and the Dominos", genre: "Blues Rock" },
  { name: "Back in Black", artist: "AC/DC", genre: "Hard Rock" },
  { name: "Purple Haze", artist: "Jimi Hendrix", genre: "Psychedelic Rock" },
  { name: "Paranoid", artist: "Black Sabbath", genre: "Heavy Metal" },
  { name: "Gimme Shelter", artist: "The Rolling Stones", genre: "Rock" },
  { name: "All Along the Watchtower", artist: "Jimi Hendrix", genre: "Rock" },
  { name: "Born to Be Wild", artist: "Steppenwolf", genre: "Rock" },
  { name: "The Joker", artist: "Steve Miller Band", genre: "Rock" },
  { name: "Rock and Roll", artist: "Led Zeppelin", genre: "Classic Rock" },
  { name: "Tush", artist: "ZZ Top", genre: "Blues Rock" },
  { name: "Sweet Home Alabama", artist: "Lynyrd Skynyrd", genre: "Southern Rock" },
  { name: "Jumpin' Jack Flash", artist: "The Rolling Stones", genre: "Rock" },
  { name: "Black Dog", artist: "Led Zeppelin", genre: "Classic Rock" },
  { name: "Runnin' with the Devil", artist: "Van Halen", genre: "Hard Rock" }
];
